# Etapa de construção
FROM node:18-slim as build
WORKDIR /usr/src/app
COPY . .
RUN npm install --quiet --no-optional --no-fund --loglevel=error
RUN npm run build

# Etapa de produção
FROM nginx:stable-alpine
# Copia os arquivos construídos
COPY --from=build /usr/src/app/dist /usr/share/nginx/html
# Copia a configuração personalizada do Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 5173
CMD ["nginx", "-g", "daemon off;"]
